M48
; DRILL file {KiCad (6.0.5-0)} date Monday, 27 June 2022 at 15:48:47
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-27T15:48:47+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C5.000
%
G90
G05
T1
X53.975Y-66.675
X127.635Y-66.675
T3
X90.8Y-47.8
T2
X84.55Y-49.8G85X97.05Y-49.8
G05
T0
M30
